server:
  port: 30304

# spring 配置
spring:
  application:
    name: alinesno-infra-smart-assistant-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_alinesno_infra_smart_assistant_v100?characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password:  adminer
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local
  devtools:
    restart:
      enabled: true

actable:
  table:
    auto: update
  model:
    pack: com.alinesno.infra.smart.assistant.entity
  database:
    type: mysql
  index:
    prefix: alinesno_smart_assistant_idx_
  unique:
    prefix: alinesno_smart_assistant_uni_


# sa-token配置
sa-token:
  token-name: satoken
  host-path: http://alinesno-infra-base-identity-auth-application.beta.base.infra.linesno.com
  sso:
    auth-url: ${sa-token.host-path}/login
    is-http: true
    check-ticket-url: ${sa-token.host-path}/sso/checkTicket
    slo-url: ${sa-token.host-path}/sso/signout
    get-data-url: ${sa-token.host-path}/sso/getData
  sign:
    secret-key:

# wechat token
alinesno.infra:
  gateway:
    host:
  smart:
    dingtalk:
      app-key:
      app-secret:
      robot-code:
    wechat:
      token: xxxxx

# liteflow 配置
liteflow:
  print-banner: false
  rule-source-ext-data-map:
    applicationName: ${spring.application.name}

    #是否开启SQL日志
    sqlLogEnabled: true

    #以下是chain表的配置，这个一定得有
    chainTableName: role_chain
    chainApplicationNameField: chain_application_name
    chainNameField: chain_name
    elDataField: el_data
    chainEnableField: enable

    #以下是script表的配置，如果你没使用到脚本，下面可以不配置
    scriptTableName: role_chain_script
    scriptApplicationNameField: application_name
    scriptIdField: script_id
    scriptNameField: script_name
    scriptDataField: script_data
    scriptTypeField: script_type
    scriptLanguageField: script_language
    scriptEnableField: enable
