server:
  port: 30304

# spring 配置
spring:
  application:
    name: alinesno-infra-smart-assistant-boot
  devtools:
    restart:
      enabled: true

# wechat token
alinesno.infra.smart:
  wechat:
    token: xxxxx