server:
  port: 30304

# spring 配置
spring:
  application:
    name: alinesno-infra-smart-assistant-boot
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local
  devtools:
    restart:
      enabled: true

# wechat token
alinesno.infra.smart:
  wechat:
    token: xxxxx